version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    image: app:code
    container_name: pharmacy
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - redis
    networks:
      - med_network

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - med_network

networks:
  med_network:
    driver: bridge
