version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./caches:/code/caches       #ensures cache data persists
      - ./database:/code/database   # ensures database data persists
    ports:
      - 8000:8000
    container_name: test_2
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
