# Generated by Django 4.2.9 on 2024-01-07 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='expiration_yyyymmdd',
            new_name='expiration_date',
        ),
    ]
